Udemy/Full_Stack/django_level_five/learning_user_auth/basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('register', views.register, name='register'),
]

Udemy/Full_Stack/django_level_five/learning_user_auth/learning_user_auth/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
]

Udemy/Full_Stack/django_level_five/learning_user_auth/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

Udemy/Full_Stack/django_level_five/learning_user_auth/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = (
            'username',
            'email',
            'password',
        )


class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = (
            'portfolio_site',
            'profile_pic',
        )

Udemy/Full_Stack/django_level_five/learning_user_auth/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm


def index(request):
    return render(request, 'basic_app/index.html')


def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(
                user_form.errors,
                profile_form.errors
            )

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(
        request, 'basic_app/registration.html',
        {
            'user_form': user_form,
            'profile_form': profile_form,
            'registered': registered
        }
    )

Udemy/Full_Stack/django_level_five/learning_user_auth/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  <body>

    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">LOGO</a>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic_app:register' %}">Sign up</a>
            </li>
            <!-- <li class="nav-item">
              <a class="nav-link" href="#">Log in</a>
            </li> -->
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}
      {% endblock %}

    </div>

  </body>
</html>

Udemy/Full_Stack/django_level_five/learning_user_auth/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron-fluid mt-5">
  <h1 class="display-4">Home page</h1>
  <p class="lead">Welcome to the random home page</p>
  <hr>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

{% endblock %}

Udemy/Full_Stack/django_level_five/learning_user_auth/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron-fluid mt-5">
  {% if registered %}

    <h1 class="display-4">You're all registered!</h1>
    <p class="lead">Feel free to poke around.</p>

  {% else %}

    <h1 class="display-4">Register here.</h1>
    <p class="lead">Fill out the form.</p>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>

  {% endif %}

</div>

{% endblock %}