Udemy/Full_Stack/django_level_four/template_project/basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

Udemy/Full_Stack/django_level_four/template_project/template_project/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
]

Udemy/Full_Stack/django_level_four/template_project/basic_app/views.py
from django.shortcuts import render


def index(request):
    context_dict = {
        'text': 'Hello world!',
        'number': 100,
    }
    return render(request, 'basic_app/index.html', context_dict)


def other(request):
    return render(request, 'basic_app/other.html')


def relative(request):
    return render(request, 'basic_app/relative_url_template.html')

Udemy/Full_Stack/django_level_four/template_project/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>

    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  <body>

    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">BRAND</a>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic_app:other' %}">Other</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic_app:relative' %}">Relative</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">

      {% block body_block %}

      <!-- Anything outside of this will be inherited -->

      {% endblock %}

    </div>

  </body>
</html>

Udemy/Full_Stack/django_level_four/template_project/templates/basic_app/index.html
<!DOCTYPE html>

{% extends "basic_app/base.html" %}
{% load my_custom_template_tags %}

  {% block body_block %}

    <h1 class="display-4 mt-5">Welcome to the Home page!</h1>
    <h3>{{ text|cut:'o' }}</h3>
    <h4>This is a number: {{ number|add:"1" }}</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  {% endblock %}

Udemy/Full_Stack/django_level_four/template_project/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

  {% block body_block %}

    <h1 class="display-4 mt-5">Welcome to Other!</h1>
    <div class="row">
      <div class="col-md-6">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
      <div class="col-md-6">
        <p class="lead">
        Here are some useless buttons!<br>
        Click them to relieve some stress.
        </p>
        <button type="button" class="btn btn-info btn-md btn-block" name="button">Button</button>
        <button type="button" class="btn btn-info btn-md btn-block" name="button">Another Button</button>
        <button type="button" class="btn btn-info btn-md btn-block" name="button">Buttons Buttons</button>
      </div>
    </div>

  {% endblock %}

Udemy/Full_Stack/django_level_four/template_project/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}

  {% block body_block %}

    <h1 class="display-4 mt-5">Welcome to URL Templates!</h1>
    <p class="lead">Read some interesting stuff.</p>
    <div class="row mt-3">
      <div class="col-md-3">
        <h4>TEXT 1</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
      <div class="col-md-3">
        <h4>TEXT 2</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
      <div class="col-md-3">
        <h4>TEXT 3</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
      <div class="col-md-3">
        <h4>TEXT 4</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </div>
    </div>

  {% endblock %}