Udemy/Full_Stack/django_level_three/exercise_project/exercise_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'))
]

Udemy/Full_Stack/django_level_three/exercise_project/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('', views.home, name='home'),
    path('users/', views.users, name='users'),
]

Udemy/Full_Stack/django_level_three/exercise_project/users/models.py
from django.db import models

class User(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.email

Udemy/Full_Stack/django_level_three/exercise_project/users/forms.py
from . import models
from django import forms
from django.core import validators


class NewUserForm(forms.ModelForm):

    class Meta():
        model = models.User
        fields = '__all__'

Udemy/Full_Stack/django_level_three/exercise_project/users/views.py
from django.shortcuts import render
from users.models import User
from users.forms import NewUserForm


def home(request):
    return render(request, 'users/index.html')


def users(request):
    form = NewUserForm()

    if request.method == "POST":                # if the user hits submit on form
        form = NewUserForm(request.POST)

        if form.is_valid():                     # and if that form is valid...
            form.save(commit=True)
            return home(request)

        else:
            print("ERROR: Form invalid.")

    return render(request, 'users/users.html', {'form': form})

Udemy/Full_Stack/django_level_three/exercise_project/templates/users/index.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home</title>

    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>
  <body>

    <div class="container mt-5">
      <h1 class="display-4">This is the index home page.</h1>
      <p class="lead"><a href="{% url 'users:users' %}">Follow this link</a> to the login page.</p>
      <hr>
    </div>

  </body>
</html>

Udemy/Full_Stack/django_level_three/exercise_project/templates/users/users.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Users</title>

    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- My CSS -->
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">

  </head>
  <body>

    <div class="container mt-5">
      <h1 class="display-4">Sign up!</h1>
      <form class="mt-3" method="POST">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" name="btn btn-info" value="Submit">
      </form>
    </div>

  </body>
</html>